### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by floweryht** [HaoguangYang/omniveyor_gazebo_world#1]
When I try to catkin_make this project, I see these error messages:

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - omniveyor_common
-- ~~  - omniveyor_gazebo_world
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'omniveyor_common'
-- ==> add_subdirectory(omniveyor_common)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /opt/ros/noetic/share/catkin/cmake/assert.cmake:20 (message):
  

  Assertion failed: file
  '/home/htyun/catkin_ws/src/omniveyor_common/action/HighLevelTask.action'
  does not exist.  Message: action file not found

Call Stack (most recent call first):
  /opt/ros/noetic/share/actionlib_msgs/cmake/actionlib_msgs-extras.cmake:35 (assert_file_exists)
  omniveyor_common/CMakeLists.txt:69 (add_action_files)

-- Configuring incomplete, errors occurred!
See also "/home/htyun/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/htyun/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:320: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by HaoguangYang** [comment]
Should be fixed now with the latest commit. Please re-run the rosinstall command to pull new changes, and then re-compile.

**Comment by HaoguangYang** [comment]
> When I try to catkin_make this project, I see these error messages:
> 
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -- ~~ traversing 2 packages in topological order: -- ~~ - omniveyor_common -- ~~ - omniveyor_gazebo_world -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -- +++ processing catkin package: 'omniveyor_common' -- ==> add_subdirectory(omniveyor_common) -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy CMake Error at /opt/ros/noetic/share/catkin/cmake/assert.cmake:20 (message):
> 
> Assertion failed: file '/home/htyun/catkin_ws/src/omniveyor_common/action/HighLevelTask.action' does not exist. Message: action file not found
> 
> Call Stack (most recent call first): /opt/ros/noetic/share/actionlib_msgs/cmake/actionlib_msgs-extras.cmake:35 (assert_file_exists) omniveyor_common/CMakeLists.txt:69 (add_action_files)
> 
> -- Configuring incomplete, errors occurred! See also "/home/htyun/catkin_ws/build/CMakeFiles/CMakeOutput.log". See also "/home/htyun/catkin_ws/build/CMakeFiles/CMakeError.log". make: *** [Makefile:320: cmake_check_build_system] Error 1 Invoking "make cmake_check_build_system" failed

If no further errors regarding compilation appears, I would go ahead and close this issue.
